Hamburg
===================================== 

```{r}
Datum <- as.Date('2018-03-11')
base_data <- data_hamburg[data_hamburg$DATUM==Datum,]
monthly_reference <- calculate_reference(data_hamburg)
```

Column {data-width=80}
----------------------------

### Date

```{r}
valueBox(Datum,
         color='blue')
```

### 5 cm 

```{r}
boxvalue <- base_data$cm_05[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_05[monthly_reference$month==this_month]
valueBox(round(boxvalue,digits=2),
         icon = "fa-globe", 
         color=ifelse(boxvalue<refvalue,"danger","success"))
```

### 10 cm 

```{r}
boxvalue <- base_data$cm_10[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_10[monthly_reference$month==this_month]
valueBox(round(boxvalue,digits=2),
         icon = "fa-globe", 
         color=ifelse(boxvalue<refvalue,"danger","success"))
```

### 20 cm 

```{r}
boxvalue <- base_data$cm_20[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_20[monthly_reference$month==this_month]
valueBox(round(boxvalue,digits=2),
         icon = "fa-globe", 
         color=ifelse(boxvalue<refvalue,"danger","success"))
```

### 50 cm 

```{r}
boxvalue <- base_data$cm_50[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_50[monthly_reference$month==this_month]
valueBox(round(boxvalue,digits=2),
         icon = "fa-globe", 
         color=ifelse(boxvalue<refvalue,"danger","success"))
```

Column {data-width=80}
----------------------------

### Reference

```{r}
valueBox(months(Datum),
         color='blue')
```

### 5 cm 

```{r}
this_month <- months(Datum)
refvalue <- monthly_reference$cm_05[monthly_reference$month==this_month]
valueBox(round(refvalue,digits=2),
         icon = "fa-heartbeat")
```

### 10 cm 

```{r}
this_month <- months(Datum)
refvalue <- monthly_reference$cm_10[monthly_reference$month==this_month]
valueBox(round(refvalue,digits=2),
         icon = "fa-heartbeat")
```

### 20 cm 

```{r}
this_month <- months(Datum)
refvalue <- monthly_reference$cm_20[monthly_reference$month==this_month]
valueBox(round(refvalue,digits=2),
         icon = "fa-heartbeat")
```

### 50 cm 

```{r}
this_month <- months(Datum)
refvalue <- monthly_reference$cm_50[monthly_reference$month==this_month]
valueBox(round(refvalue,digits=2),
         icon = "fa-heartbeat")
```

Column {data-width=80}
----------------------------

### Delta

```{r}
valueBox('Difference',
         color='blue')
```

### 5 cm 

```{r}
boxvalue <- base_data$cm_05[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_05[monthly_reference$month==this_month]
valueBox(round(boxvalue-refvalue,digits=2),
         icon = "fa-calculator")
```

### 10 cm 

```{r}
boxvalue <- base_data$cm_10[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_10[monthly_reference$month==this_month]
valueBox(round(boxvalue-refvalue,digits=2),
         icon = "fa-calculator")
```

### 20 cm 

```{r}
boxvalue <- base_data$cm_20[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_20[monthly_reference$month==this_month]
valueBox(round(boxvalue-refvalue,digits=2),
         icon = "fa-calculator")
```

### 50 cm 

```{r}
boxvalue <- base_data$cm_50[1]
this_month <- months(Datum)
refvalue <- monthly_reference$cm_50[monthly_reference$month==this_month]
valueBox(round(boxvalue-refvalue,digits=2),
         icon = "fa-calculator")
```
