Daily
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

Reporting - Daily Overview 

```{r}
dateInput("datum","Choose Date:",min='2016-11-12',max='2018-05-15',value='2018-05-15')
```

Column {data-width=80}
----------------------------

### Date

```{r}
Datum <- reactive(get(input$reporting_date))
valueBox(Datum,
         color='blue')
```

<!-- ### Revenue -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$REVENUE[1] -->
<!-- refvalue <- reference_week$REVENUE[1] -->
<!-- valueBox(round(boxvalue,digits=0), -->
<!--          href = '#section-revenue-14', -->
<!--          icon = "fa-euro", -->
<!--          color = ifelse(boxvalue<alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- ### Impressions -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$IMPRESSIONS[1] -->
<!-- refvalue <- reference_week$IMPRESSIONS[1] -->
<!-- valueBox(round(boxvalue,digits=0),  -->
<!--          href = '#section-impressions-12', -->
<!--          icon = "fa-globe", -->
<!--          color = ifelse(boxvalue < alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- ### eRPI -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$eRPI[1] -->
<!-- refvalue <- reference_week$eRPI[1] -->
<!-- valueBox(round(boxvalue,digits=4),  -->
<!--          href = '#section-rpi', -->
<!--          icon = "fa-calculator", -->
<!--          color = ifelse(boxvalue < alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- ### Clicks -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$CLICKS[1] -->
<!-- refvalue <- reference_week$CLICKS[1] -->
<!-- valueBox(round(boxvalue,digits=0),  -->
<!--          href = '#section-clicks-12', -->
<!--          icon = "fa-mouse-pointer", -->
<!--          color = ifelse(boxvalue<alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- ### Daily Budget -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$DAILY_BUDGET[1] -->
<!-- refvalue <- reference_week$DAILY_BUDGET[1] -->
<!-- valueBox(round(boxvalue,digits=0),  -->
<!--          href = '#section-budgets', -->
<!--          icon = "fa-euro", -->
<!--          color = ifelse(boxvalue<alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- ### eCPC -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$eCPC[1] -->
<!-- refvalue <- reference_week$eCPC[1] -->
<!-- valueBox(round(boxvalue,digits=2),  -->
<!--          href = '#section-prices', -->
<!--          icon = "fa-calculator", -->
<!--          color = ifelse(boxvalue<alerting_threshold*refvalue, "danger",  -->
<!--                         ifelse(boxvalue<refvalue & boxvalue>=alerting_threshold*refvalue, "warning","success") -->
<!--                         ) -->
<!--          ) -->
<!-- ``` -->

<!-- Column {data-width=40} -->
<!-- ---------------------------- -->

<!-- ### Reference Weekday -->

<!-- ```{r} -->
<!-- Datum <- weekdays(base_data[1,1]) -->
<!-- valueBox(Datum,  -->
<!--          icon = "fa-address-book", -->
<!--          color = 'blue') -->

<!-- ``` -->

<!-- ### Revenue -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$REVENUE[1] -->
<!-- valueBox(round(refvalue,digits=0),  -->
<!--          icon = "fa-euro" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Impressions -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$IMPRESSIONS[1] -->
<!-- valueBox(round(refvalue,digits=0),  -->
<!--          icon = "fa-globe" -->
<!--          ) -->
<!-- ``` -->

<!-- ### eRPI -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$eRPI[1] -->
<!-- valueBox(round(refvalue,digits=4),  -->
<!--          icon = "fa-calculator" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Clicks -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$CLICKS[1] -->
<!-- valueBox(round(refvalue,digits=0),  -->
<!--          icon = "fa-mouse-pointer" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Daily Budget -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$DAILY_BUDGET[1] -->
<!-- valueBox(round(refvalue,digits=0),  -->
<!--          icon = "fa-euro" -->
<!--          ) -->
<!-- ``` -->

<!-- ### eCPC -->

<!-- ```{r} -->
<!-- refvalue <- reference_week$eCPC[1] -->
<!-- valueBox(round(refvalue,digits=2),  -->
<!--          icon = "fa-calculator" -->
<!--          ) -->
<!-- ``` -->

<!-- <!-- ### eCPM --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- refvalue <- reference_week$eCPM[1] --> -->
<!-- <!-- valueBox(round(refvalue,digits=2),  --> -->
<!-- <!--          icon = "fa-calculator" --> -->
<!-- <!--          ) --> -->
<!-- <!-- ``` --> -->

<!-- Column {data-width=40} -->
<!-- ---------------------------- -->

<!-- ### Delta -->

<!-- ```{r} -->
<!-- valueBox("Delta",  -->
<!--          icon = "fa-address-book", -->
<!--          color = 'blue') -->

<!-- ``` -->

<!-- ### Revenue -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$REVENUE[1] -->
<!-- refvalue <- reference_week$REVENUE[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-euro" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Impressions -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$IMPRESSIONS[1] -->
<!-- refvalue <- reference_week$IMPRESSIONS[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-globe" -->
<!--          ) -->
<!-- ``` -->

<!-- ### eRPI -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$eRPI[1] -->
<!-- refvalue <- reference_week$eRPI[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-calculator" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Clicks -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$CLICKS[1] -->
<!-- refvalue <- reference_week$CLICKS[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-mouse-pointer" -->
<!--          ) -->
<!-- ``` -->

<!-- ### Daily Budget -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$DAILY_BUDGET[1] -->
<!-- refvalue <- reference_week$DAILY_BUDGET[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-euro" -->
<!--          ) -->
<!-- ``` -->

<!-- <!-- ### Total Budget --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- boxvalue <- base_data$TOTAL_BUDGET[1] --> -->
<!-- <!-- refvalue <- reference_week$TOTAL_BUDGET[1] --> -->
<!-- <!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  --> -->
<!-- <!--          icon = "fa-euro" --> -->
<!-- <!--          ) --> -->
<!-- <!-- ``` --> -->

<!-- ### eCPC -->

<!-- ```{r} -->
<!-- boxvalue <- base_data$eCPC[1] -->
<!-- refvalue <- reference_week$eCPC[1] -->
<!-- valueBox(paste(round(100*(boxvalue-refvalue)/refvalue,digits=2),'%'),  -->
<!--          icon = "fa-calculator" -->
<!--          ) -->
<!-- ``` -->

<!-- Column <!-- {data-width=200} --> -->
<!-- ------------------------------------- -->

<!-- ### Revenue -->

<!-- ```{r} -->
<!-- valueBox('Overview Chart',  -->
<!--          icon = "fa-address-book", -->
<!--          color =  'blue' -->
<!--          ) -->
<!-- ``` -->

<!-- ###  -->

<!-- ```{r} -->
<!-- concrete_metric <- base_data[,c("DATUM","WEEKDAY_ID","REVENUE")] -->
<!-- starting_date <- today()-number_of_days -->
<!-- plot_revenue_overview <- create_demo_plot_generic(concrete_metric = concrete_metric,starting_date = starting_date) -->
<!-- plot_predefined_plot(plot_revenue_overview) -->
<!-- ```    -->
